### ISSUE TITLE
Update to include git-describe

### ISSUE THREAD

**Issue by rafecolton** [libgit2/git2go#120]
Now that https://github.com/libgit2/libgit2/pull/2592 has been merged :smile:

**Comment by carlosmn** [comment]
The release of libgit2 v0.22 makes describe accessible via master, if you'd like to add this functionality.

**Comment by rafecolton** [comment]
No, I would not like to add this functionality.  I would like the maintainers of the library to add this functionality...eight months ago when I originally filed the issue.  I stopped using this library a long time ago

**Comment by clns** [comment]
PR created #227
