### ISSUE TITLE
how to checkout a local branck

### ISSUE THREAD

**Issue by rpau** [libgit2/git2go#142]
Hi,

I am intrested in  writting a code that creates a local branch and applies a set of changes in that branch. Hence, I need to apply checkout once I have created a branch. I am pretty lost with this API and I haven't found examples in the test files to do that. I will appreciate any help :-)

This is my code and the call LookupTree crashes with the error message "The requested type does not match the type in ODB".

---

```
branch, _ := repo.CreateBranch("mybranch", currentTip, true, sig, message)

checkOutOpts := &git.CheckoutOpts{
        Strategy: git.CheckoutForce,
        FileOpenFlags : os.O_WRONLY,
    }
tree, _ := repo.LookupTree(branch.Target())
if err != nil {
    fmt.Print(err)
}
repo.CheckoutTree(tree, checkOutOpts)
```

---

**Comment by cleung2010** [comment]
@rpau did you figure how to do it with the `CheckoutTree()` method? I want to creating a HEAD ref for the the branch if possible.
