### ISSUE TITLE
Consider making this package go gettable?

### ISSUE THREAD

**Issue by shurcooL** [libgit2/git2go#143]
Right now, this package requires custom manual steps for its installation:

> Run `go get -d github.com/libgit2/git2go` to download the code and go to your `$GOPATH/src/github.com/libgit2/git2go` dir. From there, we need to build the C code and put it into the resulting go binary.
>
>     git submodule update --init # get libgit2
>     make install
>
> will compile libgit2 and run `go install` such that it's statically linked to the git2go package.

This is inconvenient, it makes it harder to get than other Go packages (which are just `go get`). Worst of all, this means that _any_ other Go package that imports this one, even if the upstream package is completely go gettable, will no longer be 1 command to install.

I _think_ it may be possible for you to change that, and thus improve the experience of anyone using this packages, and make it easy for others to import it and no incur the cost of manual dependency installation steps.

The way you can do that would be similar to how we did it with [glfw3 package](https://github.com/go-gl/glfw3/tree/devel_glfw3.1) (currently on a branch, to be merged into master once GLFW 3.1 is released), which is a Go binding for a C library. It was discovered by @slimsag and you can see the discussion in the following issue and PR:

https://github.com/go-gl/glfw3/issues/82
https://github.com/go-gl/glfw3/pull/83

The general idea is that you vendor the C library source in a subfolder (potentially as a git submodule) and use cgo directives to link to it. Basically, everything you're doing now, except without needing the Makefile and scripts.

The main consideration is that you will need to replace the function of CMake with multiple .go files with build tags (which may require some work and maintenance), which is what we've done in glfw3:

> > Less configurable? Unable to modify CMAKE parameters?

> Actually -- We can make build tags for any CMAKE configurable feature that we want (e.g. tell people to compile their application with `go install -tags "wayland" my/pkg` and a wayland client will be built instead of an X11 one, you can see how I did this here: https://github.com/go-gl/glfw3/blob/devel_glfw3.1/build.go)

But the end result is a go gettable package that is much easier for users. Just imagine:

> To install `git2go`, run `go get -u github.com/libgit2/git2go`. Done.

What do you think? If this is something you're amendable to, I can assist with questions/answers about the approach and potentially try to make a PR.

**Comment by carlosmn** [comment]
Now that libgit2 v0.22 is released, I've made a `v22` branch which will dynamically link to libgit2. You can use

    import "gopkg.in/libgit2/git2go.v22"

to get a version of git2go which will work against the system libraries and thus the go tool will like.

**Comment by kron4eg** [comment]
@carlosmn so, with merge v22 into master now static linking is eliminated... which is very unfortunately.

**Comment by kron4eg** [comment]
@carlosmn any suggestions to workaround?

**Comment by carlosmn** [comment]
As master follows the releases, there is no need for static linking. If you would like that, you can use the `next` branch at whichever commit you prefer.

**Comment by shurcooL** [comment]
Have you considered this and decided it won't be done?

**Comment by carlosmn** [comment]
See this issue and the README for how this package can be built with the standard Go toolchain.
