### ISSUE TITLE
could not determine kind of name for C.GIT_CHECKOUT_SAFE_CREATE

### ISSUE THREAD

**Issue by shawnl** [libgit2/git2go#181]
```
commit 98793509039cc80b774c527d9e5a7b5d70e3b6c4
Author: Shawn Landden <shawn@churchofgit.com>
Date:   Sat Mar 14 15:42:25 2015 -0700

    GIT_CHECKOUT_SAFE_CREATE has been removed in libgit2
    
    Signed-off-by: Shawn Landden <shawn@churchofgit.com>

diff --git a/checkout.go b/checkout.go
index 6eb6098..9456168 100644
--- a/checkout.go
+++ b/checkout.go
@@ -15,7 +15,6 @@ type CheckoutStrategy uint
 const (
        CheckoutNone                      CheckoutStrategy = C.GIT_CHECKOUT_NONE                         // Dry run, no actual updates
        CheckoutSafe                      CheckoutStrategy = C.GIT_CHECKOUT_SAFE                         // Allow safe updates that cannot overwrite uncommitted data
-       CheckoutSafeCreate                CheckoutStrategy = C.GIT_CHECKOUT_SAFE_CREATE                  // Allow safe updates plus creation of missing files
        CheckoutForce                     CheckoutStrategy = C.GIT_CHECKOUT_FORCE                        // Allow all updates to force working directory to look like index
        CheckoutAllowConflicts            CheckoutStrategy = C.GIT_CHECKOUT_ALLOW_CONFLICTS              // Allow checkout to make safe updates even if conflicts are found
        CheckoutRemoveUntracked           CheckoutStrategy = C.GIT_CHECKOUT_REMOVE_UNTRACKED             // Remove untracked files not in index (that are not ignored)
```

**Comment by shawnl** [comment]
Sorry about the formatting. I hate github pull requests.

**Comment by carlosmn** [comment]
This is just one change that would have to be made to let the master branch build with libgit2's master, but this doesn't update the bundled libgit2 to a version which would need this change so it's just removing some functionality which we do ship with.

**Comment by b35li** [comment]
Yeah, I got this error when I run "go install" in git2go. Do you know what version of git2go to use? Now I am working on master branch.

**Comment by b35li** [comment]
When I checked out to next, I saw the change above, when will you merge to master? Otherwise ,what version of libgit2 I should use?

**Comment by carlosmn** [comment]
See the README file for which branch goes with with libgit2 branch. `next` will be merged to master when libgit2 makes a release with those changes in it.

**Comment by carlosmn** [comment]
This change is now in `next` along with the rest of changes needed to make it compile against libgit2 `master`, so I'm going to close this.

**Comment by shawnl** [comment]
upsteam became incompatible again:
./merge.go:100: opts.flags undefined (type *C.struct___2 has no field or method flags)
./merge.go:126: unknown C.struct___2 field 'flags' in struct literal
./merge.go:336: cannot use C.git_merge_file_flags_t(options.Flags) (type C.git_merge_file_flags_t) as type C.uint in assignment

**Comment by b35li** [comment]
@carlosmn Thanks. Got it, wonderful.

**Comment by b35li** [comment]
@carlosmn  when will the changes merge to master and make a release?

**Comment by shawnl** [comment]
When upstream makes a release

**Comment by carlosmn** [comment]
The `master` branch for libgit2 did move, but that doesn't matter because git2go has the submodule with the working version.

**Comment by tony** [comment]
I was able to fix this by moving checking out ``v0.22.2`` (the latest stable release available through git tags) for libgit2.

**Comment by gbbr** [comment]
On branch `next` I get:
```
# github.com/libgit2/git2go
could not determine kind of name for C.GIT_ECONFLICT
```

**Comment by carlosmn** [comment]
It looks like you forgot to run `git submodule update`

**Comment by gbbr** [comment]
Even with `git submodule update` the same thing happens on OS X

**Comment by gbbr** [comment]
Nevermind, I had to RTFM :) Thanks

**Comment by gr4y** [comment]
I didn't want to create an new issue, so I just dug that old issue out of the trash. Sorry, about that. 

```
$ ~/git-webhook[master]: go get gopkg.in/libgit2/git2go.v22
# gopkg.in/libgit2/git2go.v22
could not determine kind of name for C.GIT_CHECKOUT_SAFE_CREATE
```
go version: `go1.4.2 darwin/amd64`

I don't have any submodules to update, so I can't do that.

**Comment by gr4y** [comment]
So I found out that home-brew provides version 0.23.0, so I installed 0.22.3 manually and pinned it for now.

**Comment by phonyphonecall** [comment]
@gr4y that worked perfect for me. Thanks! :+1:

**Comment by eddflrs** [comment]
Ran into this issue, solved by @gr4y above. Thanks.
