### ISSUE TITLE
Incredibly slow import?

### ISSUE THREAD

**Issue by tdavis** [libgit2/git2go#182]
It takes about 8 seconds to import git2go, even if I'm not using it (i.e. `go` bails afterward due to unused import). This happens when using 0.22 against libgit2 0.22.1. I have tried linking to libgit2 built as a CMake dependency as well as to a globally-installed native package.

**Comment by carlosmn** [comment]
What can git2go do here? Isn't this a factor of the go toolchain taking long to process it?

**Comment by tdavis** [comment]
I'm not sure, honestly. If I run `go build` beforehand it speeds up the import somewhat, but it just seems like a remarkably long time... so I remarked ;)

**Comment by AlbinOS** [comment]
@tdavis, did you find something to do about this ? I have the same problem, with latest version of go, libgit2 and git2go.

**Comment by cleung2010** [comment]
I am having the same issue with `go test`. The actual tests takes milliseconds (~50ms), but the process take around 10-20 seconds.

**Comment by tdavis** [comment]
I don't really use Go anymore, but IIRC it just takes a hell of a long time to compile git2go. Build it ahead of time and make sure it's available in GOPATH and doesn't get cleaned with your project.

**Comment by cleung2010** [comment]
@tdavis I am using `import "gopkg.in/libgit2/git2go.v24"`. You mean I should `go build` that package? I am still getting slow tests after this.
