### ISSUE TITLE
Private repo authentication fails

### ISSUE THREAD

**Issue by mattkrea** [libgit2/git2go#186]
Hopefully this isn't a dupe--I browsed the existing issues (closed & open) and saw nothing.

Here goes:

For our company we have **mostly** private repos. I know I can get this working *and I did* with HTTPS authentication but instead of having to put usernames and passwords for a Github machine user all over the place I'd prefer this service used a read-only user key.

First, I tried cloning directly but I consistently get:
```
2015/03/22 13:23:46 Remote error:
  Repository not found.
```

Then, I tried creating a repo, adding a remote, setting callbacks and then performing a fetch. This resulted in the same issue. Has anyone been able to work this out?

```go
func Clone(repository string, path string) error {

	cbs := &git.RemoteCallbacks{
		CredentialsCallback:      credentialsCallback,
		CertificateCheckCallback: certificateCheckCallback,
	}

	// opts := &git.CloneOptions{
	// 	RemoteCallbacks: cbs,
	// }

	signature := &git.Signature{
		Name:  "Matthew Rea",
		Email: "mrea@harbortouch.com",
		When:  time.Now(),
	}

	repo, err := git.InitRepository(path, true)
	if err != nil {
		return err
	}

	remote, err := repo.CreateRemote("origin", repository)
	if err != nil {
		return err
	}

	err = remote.SetCallbacks(cbs)
	if err != nil {
		return err
	}

	specs, err := remote.FetchRefspecs()
	if err != nil {
		return err
	}

	err = remote.Fetch(specs, signature, "")
	if err != nil {
		return err
	}

	return nil
}

func credentialsCallback(url string, username string, allowedTypes git.CredType) (git.ErrorCode, *git.Cred) {
	// Tried my OS X username, Github username and 'git' here
	// I also tried git.NewCredSshKeyFromAgent below
	ret, cred := git.NewCredSshKey("git", "~/.ssh/id_rsa.pub", "~/.ssh/id_rsa", "")
	return git.ErrorCode(ret), &cred
}

// Made this one just return 0 during troubleshooting...
func certificateCheckCallback(cert *git.Certificate, valid bool, hostname string) git.ErrorCode {
	return 0
}
```

**Comment by b35li** [comment]
@mattkrea 
you have a bad mistake in the credentialCallback.  Here is code for function NewCredSshKey().
```
func NewCredSshKey(username string, publickey string, privatekey string, passphrase string) (int, Cred) {
	cred := Cred{}
	cusername := C.CString(username)
	defer C.free(unsafe.Pointer(cusername))
	cpublickey := C.CString(publickey)
	defer C.free(unsafe.Pointer(cpublickey))
	cprivatekey := C.CString(privatekey)
	defer C.free(unsafe.Pointer(cprivatekey))
	cpassphrase := C.CString(passphrase)
	defer C.free(unsafe.Pointer(cpassphrase))
	ret := C.git_cred_ssh_key_new(&cred.ptr, cusername, cpublickey, cprivatekey, cpassphrase)
	return int(ret), cred
}
```

The first argument is the username whom you want to clone by, e.g. http://{username}@{internal address}, so here the argument is NOT 'git', I guess.

change it, and try it out. it should work.

**Comment by carlosmn** [comment]
As you mention you're talking to GitHub, "git" is the only correct username, as shown by the url they show on the site.

@mattkrea you have

        ret, cred := git.NewCredSshKey("git", "~/.ssh/id_rsa.pub", "~/.ssh/id_rsa", "")

but there is no automatic home expansion performed anywhere in the library, so you're asking the ssh library to look for a path `$PWD/~/.ssh/id_rsa`. You'll have to replace `~` with the current user's home directory path before giving the path to the library.

**Comment by mattkrea** [comment]
@carlosmn Thanks for the tip. I'm going to check this out after work tonight and close the issue if thats the case.

**Comment by mattkrea** [comment]
Unfortunately with the above (and thus "/Users/matt/.ssh/id_rsa.pub" for public key) has left me with the output below which is where Go loses me.

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x10 pc=0x481750c]

runtime stack:
runtime.gothrow(0x4538bb0, 0x2a)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 12 [syscall, locked to thread]:
runtime.cgocall_errno(0x4001c10, 0xc2082e1c00, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/cgocall.go:130 +0xf5 fp=0xc2082e1be0 sp=0xc2082e1bb8
gopkg.in/libgit2/git2go%2ev22._Cfunc_git_clone(0xc20802c2a0, 0x6863e10, 0x684c4d0, 0xc2082e1c60, 0x0)
	/Users/matt/Development/Go/src/gopkg.in/libgit2/git2go.v22/:636 +0x43 fp=0xc2082e1c00 sp=0xc2082e1be0
gopkg.in/libgit2/git2go%2ev22.Clone(0xc20825afc0, 0x3f, 0xc20829cb60, 0xf, 0xc20825ae80, 0x0, 0x0, 0x0)
	/Users/matt/Development/Go/src/gopkg.in/libgit2/git2go.v22/clone.go:42 +0x1f4 fp=0xc2082e1d78 sp=0xc2082e1c00
```

**Comment by mattkrea** [comment]
Sorry for the delay.. looks like I moved beyond the initial issue and now my only remaining problem is that it appears the git@github.com:<org>/<project>.git format is an unsupported URL format.

**Comment by carlosmn** [comment]
What do you mean by "it appears?" Is there a particular error you're getting? Is it from the server or the client? Do you have a libgit2 which supports ssh?

**Comment by mattkrea** [comment]
Looks like its because of my libgit2 build. I'm going to attempt this outside of OS X from the start. Regardless this is an entirely separate issue now. Thanks for the help @carlosmn
