### ISSUE TITLE
[Question]How to accomplish 'git ls-tree ' in git2go?

### ISSUE THREAD

**Issue by b35li** [libgit2/git2go#193]
I'd like to list all the blob and trees(recusively parse it then).

git ls-tree HEAD

Does anybody know how to get the the result in git2go?

thanks in advance.

**Comment by kron4eg** [comment]
first you need to get commit object, then get tree from it with http://godoc.org/github.com/libgit2/git2go#Commit.Tree and then there is http://godoc.org/github.com/libgit2/git2go#Tree.Walk which will recursively walk tree + all subtrees

**Comment by b35li** [comment]
@kron4eg 
Thanks, looks good.
