### ISSUE TITLE
Cloning with read only SSH key

### ISSUE THREAD

**Issue by amlwwalker** [libgit2/git2go#199]
I have a private repository that I want to clone - my server will never edit and push to the respository.
I am trying to attach to my ssh key but I get a failure. Firstly here is my code:

```
package main

import (
    git "github.com/git2go"
	"log"

)

func credentialsCallback(url string, username string, allowedTypes git.CredType) (git.ErrorCode, *git.Cred) {
    ret, cred := git.NewCredSshKey("git", "~/.ssh/id_rsa.pub", "~/.ssh/id_rsa", "")
    return git.ErrorCode(ret), &cred
}

// Made this one just return 0 during troubleshooting...
func certificateCheckCallback(cert *git.Certificate, valid bool, hostname string) git.ErrorCode {
    return 0
}

func main() {

cbs := &git.RemoteCallbacks{
    CredentialsCallback:      credentialsCallback,
    CertificateCheckCallback: certificateCheckCallback,
}

cloneOptions := &git.CloneOptions{}
cloneOptions.RemoteCallbacks = cbs
repo, err := git.Clone("git://github.com/amlwwalker/privaterepo.git", "web", cloneOptions)
        if err != nil {
                log.Panic(err)
        }
log.Print(repo)
}
```
error:
```
2015/05/08 23:28:02 Remote error:
  Repository not found.
panic: Remote error:
  Repository not found.
```

When I do `git clone git@github.com/amlwwalker/privaterepo.git` it works fine. However I cannot use that format in git2go as I get 
```
2015/05/08 23:29:35 Unsupported URL protocol
panic: Unsupported URL protocol
```

Please can someone shed some light on how this has to be done?
It works fine when the repository is public.

**Comment by carlosmn** [comment]
The URLs you're providing to git2go and git are not the same at all (assuming you mean that you run `git clone git@github.com:amlwwalker/privaterepo.git` which would be a valid ssh path).

As for the unsupported protocol error, make sure you have the dev package for libssh2 installed when you build libgit2. Otherwise, it won't be able to talk ssh.

And as for the url, you're passing `git://github.com/amlwwalker/privaterepo.git` to git2go which means to use the raw TCP transport, which does not support any authentication. If you want to use SSH, you must provide a SSH URL.

You should also pass the actual path to the keys. git2go will not perform any shell expansion on the paths you give it.

**Comment by amlwwalker** [comment]
Thanks for responding.

So I installed `lib2ssh-devel` (Im on centos) with `sudo yum install libssh2-devel`
I then re cloned libgit2 and ran these commands inside the directory:

```
mkdir build && cd build
cmake ..
sudo cmake --build . --target install
```
it seemed to install successfully.
When i change the following line in my original code:
`repo, err := git.Clone("git://github.com/amlwwalker/privaterepo.git", "web", cloneOptions)`
to
`repo, err := git.Clone("git@github.com/amlwwalker/privaterepo.git", "web", cloneOptions)`
I.e using the proper git user against github, I still get the unknown protocol error:

```
2015/05/09 01:02:48 Unsupported URL protocol
panic: Unsupported URL protocol
```
Im concerned that the reinstallation of libgit2 may not have picked up the libssh2-devel install - is there a way to confirm that?

**Comment by carlosmn** [comment]
You're still not asking git2go to use SSH. `git@github.com/amlwwalker/privaterepo.git` isn't a valid URL in any of the schemes for git or git2go. You'd need to use `git@github.com:amlwwalker/privaterepo.git` or `ssh://git@github.com/amlwwalker/privaterepo.git` for it to use SSH.

Check the CMake output to see if it detected libssh2. There's also `git_libgit2_settings()` but it doesn't look like it's currently bound by git2go.

**Comment by amlwwalker** [comment]
ahh, cool, yeah completely my mistake, sorry - forgot to swap the foward slash for the colon Seems like it is picking it up now, as I now have the error
```
Failed to authenticate SSH session: Unable to open public key file
panic: Failed to authenticate SSH session: Unable to open public key file
```
which might be permissions? If so, is it a go user that needs access to the public key, or is that something with the callback:

```
func credentialsCallback(url string, username string, allowedTypes git.CredType) (git.ErrorCode, *git.Cred) {
    ret, cred := git.NewCredSshKey("git", "~/.ssh/id_rsa.pub", "~/.ssh/id_rsa", "")
    return git.ErrorCode(ret), &cred
}
```
I'm not sure how to pass the ssh keys into the callback from main() ?

**Comment by carlosmn** [comment]
The paths you're using are unlikely to exist. As I mentioned in the first reponse, git2go does not perform any shell expansion, so it's looking for a file literally called `~/.ssh/id_rsa` relative to the app's current directory.

**Comment by amlwwalker** [comment]
ahh yep sorry! All works now!!
I have written up my notes and placed them on the server for anyone else who is struggling with this
https://golog.co/blog/article/Git2Go

**Comment by sithembiso** [comment]
For some strange reason, running @amlwwalker 's code, I get `callback returned unsupported credentials type`. I have pinned it down to this [line](https://github.com/libgit2/libgit2/blob/master/src/transports/ssh.c#L446). What I don't understand however is that if the value of `cred.Type()` in the callback matches that of `git.CredTypeSshKey`.

Could anyone shed some light as to why this fails this test:
```c
if (!(cred->credtype & auth_methods)) {
	cred->free(cred);
	giterr_set(GITERR_SSH, "callback returned unsupported credentials type");
	return -1;
}
```

**Comment by carlosmn** [comment]
Have you checked that libgit2 is asking for the that kind of authentication information? If you have not provided a username in the url, it will first ask for that. See https://libgit2.github.com/docs/guides/authentication/

**Comment by sithembiso** [comment]
Your are right. It works now. My URL previously was `ssh://example.com:/username/repo.git`. I have now changed it to `git@example.com:username/repo.git`. Thanks again!

**Comment by rcshubhadeep** [comment]
This is a little bit older now. I found that some stuffs need changing to run with the new version. This is what I ended up doing - 


```
cbs := git.RemoteCallbacks{
		CredentialsCallback:      credentialsCallback,
		CertificateCheckCallback: certificateCheckCallback,
	}

cloneOptions := &git.CloneOptions{}

cloneOptions.FetchOptions = &git.FetchOptions{}

cloneOptions.CheckoutOpts = &git.CheckoutOpts{}

cloneOptions.CheckoutOpts.Strategy = 1 //Otherwise it is dry run. Nothing really clones

cloneOptions.FetchOptions.RemoteCallbacks = cbs

repo, err := git.Clone("git@example.com:username/repo.git", "web", cloneOptions)
```

It worked for me. Let me know what you think.

Thanks for posting the first code. It saved my day. So I am posting here to save other people's day as well. 

And one last thing, now the package is called 

> github.com/libgit2/git2go
