### ISSUE TITLE
git diff using git_diff_blobs

### ISSUE THREAD

**Issue by Farioko** [libgit2/git2go#213]
In order to generate a diff patch using libgit2 I need to use git_diff_blobs(). However this seems not to be implemented in git2go yet.

This is the equivalent command I would run:

`git diff 1bf5dff57420ac6f08e9d196d3333aa0ca19f08a:file1 68f8c50f8987d0d94a0ffba82d499bf32663f774:file1`

Is there a possibility that this feature could be added? (or if there is an other way to accomplish this please point me in the right direction)

**Comment by carlosmn** [comment]
Fixed via #216. Turns out this had been on my computer for a while, and I completely forgot to push it up.

**Comment by Farioko** [comment]
Awesome! Will try it soon :)
