### ISSUE TITLE
BranchIterator.ForEach returning ErrIterOver instead of nil

### ISSUE THREAD

**Issue by kazimuth** [libgit2/git2go#215]
Finishing iteration doesn't seem like it should be an error. Note that `RevWalk.Iterate` [returns `nil`](https://github.com/libgit2/git2go/blob/master/walk.go#L173) on `ErrIterOver`, whereas `BranchIterator.ForEach` [doesn't check](https://github.com/libgit2/git2go/blob/v22/branch.go#L68) for `ErrIterOver`.

**Comment by carlosmn** [comment]
Indeed, the foreach method should convert an ITEROVER into it not being an error.

**Comment by carlosmn** [comment]
Fixed with 157593f3
