### ISSUE TITLE
`CheckoutForce` disappeared from the [next] branch

### ISSUE THREAD

**Issue by clns** [libgit2/git2go#220]
It appears there isn't a way to do a force checkout while using the [next] branch. The [`GIT_CHECKOUT_FORCE`](https://github.com/libgit2/libgit2/blob/fb84cde81e11947add4ff8bb9b4084f7d76e6567/include/git2/checkout.h#L113) option was removed in [this commit](https://github.com/libgit2/git2go/commit/c4fce1a218fd33938c0be90e939531c0a00ebf7f#commitcomment-12056614).

Is this option still available? Maybe by using a different combination of flags or something?

**Comment by carlosmn** [comment]
Solved in 28dee70. It was removed by accident when adjusting the surrounding code.
