### ISSUE TITLE
[master, next] Many .go files are not gofmt'ed.

### ISSUE THREAD

**Issue by shurcooL** [libgit2/git2go#232]
```
Your branch is up-to-date with 'origin/master'.
git2go $ gofmt -l .
checkout.go
index.go
index_test.go
```

Also on `next` branch:

```
Your branch is up-to-date with 'origin/next'.
git2go $ gofmt -l .
checkout.go
index.go
index_test.go
merge.go
odb.go
remote.go
remote_test.go
repository.go
```

I would make 2 PRs that fix it, but I think it's easier for you to do it yourself, just run `gofmt -w .` command on each branch. If you still want 2 PRs that resolve this issue, let me know and I can make them.

**Comment by carlosmn** [comment]
This was handled as part of larger breaking changes a while ago.
