### ISSUE TITLE
Error when calling LookupTag within Tags.Foreach

### ISSUE THREAD

**Issue by jgautheron** [libgit2/git2go#239]
I've been experimenting with the improved tags implementation contributed by @clns (branch `next`, [PR#222](https://github.com/libgit2/git2go/pull/222)).
Calling within `Tags.Foreach()` the `LookupTag()` method always returns the following error:
`The requested type does not match the type in the ODB`.

My goal here is to retrieve `tag.Tagger().When`.

Extract:
```go
err := r.repository.Tags.Foreach(func(name string, id *git.Oid) error {
    tag, err := r.repository.LookupTag(id)
    if err != nil {
        return err
    }
    log.Info(tag.Tagger().When)
    return nil
})
```

Suggestion: why not directly passing a `*Tag` instead of `name` in the `Foreach`?

**Comment by clns** [comment]
`name` and `id` is what libgit2 uses in the callback, this is why you get that.

It could be that you're trying to retrieve lighweight tags instead of annotated ones. The foreach will loop both, but only annotated tags can be used in `LookupTag`.

**Comment by carlosmn** [comment]
The tags collection at `Repository.Tags` iterates over the tag references. These references may point to any kind of object. If a tag reference points to a commit and you ask the repository for a tag with that id, it will return that error, as your code is asking for an impossible lookup.

**Comment by jgautheron** [comment]
OK thanks for the answers. In the mean time I found a workaround I'm not really proud of, if you have suggestions... they are most welcome!
```go
it, err := r.repository.NewReferenceIteratorGlob("refs/tags/*")
if err != nil {
    return nil, err
}

for {
    t, err := it.Next()
    if err != nil {
        // The error here is empty
        break
    }

    var cd *time.Time
    // LookupCommit works only for already pushed tags
    ref, err := r.repository.LookupCommit(t.Target())
    if err != nil {
        // If LookupCommit fails, fallback to LookupTag
        // which works only for tags not yet pushed
        reff, err := r.repository.LookupTag(t.Target())
        if err != nil {
            return nil, err
        }
        cd = &reff.Tagger().When
    } else {
        cd = &ref.Committer().When
    }

    tn := t.Shorthand()
    if semver.IsValid(tn) {
        ts = append(ts, tag{date: cd, name: tn})
    }

}
```

I believe we could make this part easier to deal with. But that depends of the goal of the `git2go` library: only to provide bindings or give some extra syntactic sugar/logic?

**Comment by carlosmn** [comment]
I don't know what the comments about pushed or unpushed tags mean in your code. What a reference points to is not affected by the state of any other repository.

Without knowing what your goal is, it's going to be hard to say whether there is a better way to achieve it. If that's the logic you need, then that's what you need; but it does seem odd to treat a committer and a tagger as equivalent.

**Comment by jgautheron** [comment]
My goal here is to retrieve a `map` of tags with their creation date.
Forget about the push/not pushed tags, I thought it was the common denominator, but it's not.
`LookupTag` works fine for every tag created manually, but for 2 tags created via Github, it returns the error `The requested type does not match the type in the ODB `.
`LookupCommit` works fine on these 2 cases, and returns the proper tag creation date, as illogical it may sound (using `co.Committer().When`).
