### ISSUE TITLE
DiffFile.Size is always 0

### ISSUE THREAD

**Issue by AaronO** [libgit2/git2go#243]
When accessing the `.OldFile` and `.NewFile` fields of a `DiffDelta` obtained through a `diff.ForEach`, their `.Size` attribute is `0`.

Looking at the code ([diffFileFromC](https://github.com/libgit2/git2go/blob/d478f4b11156feee3856938bb8d27d6097745ef9/diff.go#L62)), it seems like this comes from `libgit2` rather than `git2go` itself.

I couldn't find an issue in either repo. Is this a known bug or expected behaviour ?

**Comment by carlosmn** [comment]
The size is zero as long as libgit2 hasn't actually checked the content, which can happen when diffing trees, which do not have this information. See libgit2/rugged#449

**Comment by AaronO** [comment]
@carlosmn Thanks. That's what I was thinking, it makes sense from `libgit2`'s perspective but it renders the `.Size` field useless in many cases for end users (which is rather confusing).

Obviously this is easy to workaround with a utility function that looks up the `blob` from the `Oid` and returns it's `.Size()`, what I'm wondering is should we add such a utility method on `DiffFile` ?

**Comment by carlosmn** [comment]
The field is not one which you would typically care about. The usual way to do this would be add a flag to the diff which would make it eagerly load the blobs, with the caveat that it'd be a non-trivial performance impact for a little-needed feature.

**Comment by AaronO** [comment]
@carlosmn Yep, it's definitely not high priority. I'll close the issue for now
