### ISSUE TITLE
Auth callbacks stuck in "infinite loop"

### ISSUE THREAD

**Issue by AaronO** [libgit2/git2go#246]
## Description

Using the `next` branch and `libgit2`@`v0.23.0`. Whenever a pull/fetch/clone is executed on repo requiring authentication but the credentials are invalid, git2go/libgit2 gets stuck in a loop and calls the `CredentialsCallback` forever.

This did not happen in prior versions and only appears when using `libgit2`@`v0.23.0`

## Snippet

```go
package main

import (
	"fmt"

	"github.com/libgit2/git2go"
)

func main() {
	username := "john"
	password := "secret"
	folder := "./private-repo"
	githubUrl := "https://github.com/google/private-repo"

	// Callbacks
	callbacks := git.RemoteCallbacks{
		CredentialsCallback: makeCredentialsCallback(username, password),
	}

	// Clone options
	cloneOpts := &git.CloneOptions{
		// Remote callbacks are for auth
		FetchOptions: &git.FetchOptions{
			RemoteCallbacks: callbacks,
		},
		Bare: true,
	}

	// Do actual clone
	if _, err := git.Clone(githubUrl, folder, cloneOpts); err != nil {
		fmt.Println("Clone error:", err)
	}
}

func makeCredentialsCallback(username, password string) git.CredentialsCallback {
	return func(url string, username_from_url string, allowed_types git.CredType) (git.ErrorCode, *git.Cred) {
		fmt.Println("Calling auth callback")
		errCode, cred := git.NewCredUserpassPlaintext(username, password)
		return git.ErrorCode(errCode), &cred
	}
}
```

If you run the above code you'll see :

```
❯ go run t.go
Calling auth callback
Calling auth callback
Calling auth callback
Calling auth callback
...
```

**Comment by AaronO** [comment]
@carlosmn Any idea of what's causing this and if it's been fixed upstream ?

I noticed that if I return `git.ErrAuth` in my credentials callback, the `clone` fails with the following error: 

```
HTTP parser error: the on_headers_complete callback failed
```

That might help us locate the bug.

**Comment by carlosmn** [comment]
This is not a bug, it's by design. libgit2 will ask the caller for credentials until the client or server give up, or the credentials are accepted. It is not up to the library when to give up trying to authenticate over a connection.

There was a bug by which we did not propagate the error properly, which has been fixed in master and will be part of the next libgit2 maintenance release.

**Comment by AaronO** [comment]
Ok thanks, it makes sense for the retry logic to be the callback's responsibility.

I was puzzled by this behaviour because with previous releases, the same code would not retry but instead fail with:

```
Unexpected HTTP status code: 401
```

I tried against `libgit2`@`master` and it works as expected :)

What's the recommended way for the CredentialsCallback to "give up" ?

Looking at the docs, it would appear to be: `return git.ErrAuth, nil`, (or `git.ErrPassthrough`) but that panics because of https://github.com/libgit2/git2go/blob/next/remote.go#L214 which does not accept creds to be `nil`. Obviously that can easily be worked around by sending `&git.Cred{}`, but I guess that's not intended.

**Comment by AaronO** [comment]
I added the `nil` check in https://github.com/libgit2/git2go/pull/245

**Comment by AaronO** [comment]
@carlosmn Is there a way to get the previous error (`Unexpected HTTP status code: 401`) again ? (Rather than having to detect a retry and fail with `git.ErrAuth` on the second retry)

**Comment by carlosmn** [comment]
The previous error was a bug which wasn't caught in the unix HTTP layer. libgit2 doesn't have an option to behave like that; the retry policy is your app's decision.

We return whatever error you return from the callback, but the preferred error code is `GIT_EUSER` as that way you can know it was your code who caused the abort and you can retrieve whatever extra error information you have, if any.

**Comment by AlbinOS** [comment]
Hi,

I'm running into this case and I don't understand how to know if it's a retry or not in the callback function. 

How do you catch wrong credentials in order to abort and return the right error code ?

**Comment by AaronO** [comment]
@AlbinOS The idea is that the callback is called again so that it can try different credentials. (For example over SSH try different keys). (If you want to want to know if it's a retry or not your closure will have to keep some context)

In practice over HTTPS you often only want to try one pair of `username/password`, here's a simple function that I use to build a `git.CredentialsCallback` that behaves that way:

```go
func makeCredentialsCallback(username, password string) git.CredentialsCallback {
	// If we're trying it means the credentials are invalid
	called := false
	return func(url string, username_from_url string, allowed_types git.CredType) (git.ErrorCode, *git.Cred) {
		if called {
			return git.ErrUser, nil
		}
		called = true
		errCode, cred := git.NewCredUserpassPlaintext(username, password)
		return git.ErrorCode(errCode), &cred
	}
}
```

**Comment by AlbinOS** [comment]
@AaronO, thanks, it works ! I'm new to closures and I still not completely understand the way of it and how to take benefit of using them.

One last thing if I may, the return of my call to git.Clone function is '  ' (two blank spaces) when my credentials are wrong. It's quite hard to proper log the error with that return... Any idea why this behavior ?
