### ISSUE TITLE
On Push, getting "Must call UPLOADPACK_LS before UPLOADPACK"

### ISSUE THREAD

**Issue by jmburges** [libgit2/git2go#247]
hello!

I am trying to duplicate a repo to another remote. I'm running on `next` with the most recent libgit2 v23

So! I did a bare clone of the repo, added a new remote, and now I'm trying to push. When I push get the error `Must call UPLOADPACK_LS before UPLOADPACK`.

Any ideas? Here is my code

```
	clonedRepo.Remotes.SetUrl("origin", *githubRepo.SSHURL)
	remoteCallbacks := &git.RemoteCallbacks{
		CredentialsCallback:      credentialsCallback,
		CertificateCheckCallback: certificateCheckCallback,
	}
	newOrigin, _ := clonedRepo.Remotes.Create("new_repo", *githubRepo.SSHURL)
	newOrigin.ConnectPush(remoteCallbacks)
	refspecs := make([]string, 1)
	refspecs[0] = "*:*"
	pushOptions := &git.PushOptions{}
	pushError := newOrigin.Push(refspecs, pushOptions)
```

**Comment by carlosmn** [comment]
The underlying push function may be assuming too much about the connected state, but there's no need for you to perform some of the steps manually and then jump up a layer.

There's no need to call `ConnectPush()` unless you want to perform the steps yourself. If you want to perform a push, use `Push()` which will do it all by itself.

**Comment by jmburges** [comment]
So that's what I initially thought, but when I modify my code to be like this:

```
	clonedRepo.Remotes.SetUrl("origin", *githubRepo.SSHURL)
	newOrigin, _ := clonedRepo.Remotes.Lookup("origin")
	refspecs := make([]string, 1)
	refspecs[0] = "*:*"
	pushOptions := &git.PushOptions{}
	pushError := newOrigin.Push(refspecs, pushOptions)
	fmt.Println(pushError)
```

I then get `authentication required but no callback set`. How do I set the callbacks for the push without running `ConnectPush()`?

**Comment by jmburges** [comment]
I guess I need to wait for PR https://github.com/libgit2/git2go/pull/245?

**Comment by carlosmn** [comment]
Setting it for the initial connection wouldn't necessarily let anything after that use it, but that PR is now in, so you `Push()` will use the callback.
