### ISSUE TITLE
CredentialsCallback loop

### ISSUE THREAD

**Issue by marcinwyszynski** [libgit2/git2go#250]
I have [this code](http://pastebin.com/NEBAnQPX) stuck in a loop of calling CredentialsCallback and I'm not sure what's the matter. Can you please kindly help me understand why this is the case?

**Comment by carlosmn** [comment]
libgit2 will call the credentials callback as long as the server refuses the credentials that were sent. If you keep sending wrong credentials, it will keep refusing them.

**Comment by marcinwyszynski** [comment]
I'm wondering if there is a clever way of stopping the vicious circle in such case. One way I can think of it is having `CredentialsCallback` as a method of a struct which works only once:

```go
type CredentialsWrapper struct {
  alreadyCalled bool
  callback CredentialsCallback
}

func (c *CredentialsWrapper) credentialsCallback(url string, username string, credType git.CredType) (git.ErrorCode, *git.Cred) {
  if c.alreadyCalled {
    return git.ErrAuth, nil
  }
  c.alreadyCalled = true
  return c.callback(url, username, credType)
}
```

The only problem with that is that you would need to re-create this single use struct every time you need to connect to the remote repo.

**Comment by carlosmn** [comment]
If you have no user which can give up on authentication (or have hard-coded wrong credentials), you would have to store whether you've called it already. You can do something like what you showed, or make the callback itself a closure which closes over a local variable (which is what you're replicating here), though in the future the callbacks struct may get converted into an interface which would make this more natural as you'd pass in your own struct on which methods are called.

**Comment by marcinwyszynski** [comment]
Interfaces make sense. If I end up using this library heavily I'll probably do it myself in a fork and send a pull request upstream.
