### ISSUE TITLE
Example of creating the root commit?

### ISSUE THREAD

**Issue by chanwit** [libgit2/git2go#259]
Is there any example of how to create a root commit using `git2go`?
I've tried to mimic from `libgit2` by passing `nil` as a parent commit but it seems to be wrong.

```
commit, err := repo.CreateCommit("HEAD", signature, signature, message, tree, nil)
```

any suggestion?

**Comment by clns** [comment]
```go
commitID, err := repo.CreateCommit("HEAD", signature, signature, message, tree)
```

**Comment by chanwit** [comment]
@clns thank you. It's working now.

**Comment by trungn1** [comment]
@chanwit do you remember what you did with the commitID afterwards? doesn't this return a git2go.Oid type?

**Comment by chanwit** [comment]
@trungn1 sorry it's been 4 years and I cannot remember about it :-(
