### ISSUE TITLE
[next] Update libgit2 to improve checkout/status

### ISSUE THREAD

**Issue by clns** [libgit2/git2go#264]
Today a PR was merged into libgit2 - https://github.com/libgit2/libgit2/pull/3480 - which I think should significantly improve `checkout`.

I'm struggling with a very slow checkout (https://github.com/libgit2/libgit2sharp/issues/623#issuecomment-149261842) on Windows so I'm wondering if there's anything I can do to help updating libgit2.

**Comment by carlosmn** [comment]
An update for `next` means updating the submodule to the new tip of master and adjusting to whatever API changes have been made.

**Comment by clns** [comment]
PR #266 created.

**Comment by clns** [comment]
I can confirm that after updating to libgit2 master, the times improved significantly, from ~36s to ~5s. :+1:
