### ISSUE TITLE
Why git.MergeAnalysis returns 5?

### ISSUE THREAD

**Issue by sithembiso** [libgit2/git2go#265]
I have the following code block (some code omitted for brevity):

...
```go
mergeHeads := make([]*git.AnnotatedCommit, 1)
mergeHeads[0] = annotatedCommit
analysis, _, err := repo.MergeAnalysis(mergeHeads)
if err != nil {
	return err
}
fmt.Println(analysis)
fmt.Println(
	git.MergeAnalysisNone,
	git.MergeAnalysisNormal,
	git.MergeAnalysisUnborn,
	git.MergeAnalysisUpToDate,
	git.MergeAnalysisFastForward,
)
```
...
When I run it, it returns the following:
```
5
0 1 8 2 4
```
Does anyone know any possible reason why I'm getting `5` (which doesn't match any MergeAnalysis statuses)?
I looked in the `libgit2` source code that `git2go` links to, but I can't find any status value that evaluates to `5`.

Here is the complete code:
https://gist.github.com/sithembiso/d890d3f751029a73f2c5

**Comment by pks-t** [comment]
`MergeAnalysis` may return multiple flags at once. In your case the call to `repo.MergeAnalysis` returns the value `git.MergeAnalysisNormal | git.MergeAnalysisFastForward`, which results in the value (in binary representation) `00000001 | 00000100 = 00000101`, which equals `5`.

You may check for the different flags by performing a binary-and with result and the flags, e.g. `analysis & git.MergeAnalysisNormal != 0`.

**Comment by carlosmn** [comment]
Indeed. As @pks-t mentions, there may be multiple answers, so the method returns a bitmask of the possibilities. I've added documentation for this method in `master` to mention this fact.
