### ISSUE TITLE
Index memory leaks?

### ISSUE THREAD

**Issue by clearr** [libgit2/git2go#267]
`Index` has [`Free()`](https://github.com/libgit2/git2go/blob/3b5633de219eec2908723a8e557758cc055d84d1/index.go#L317-L320) method and [`newIndexFromC()`](https://github.com/libgit2/git2go/blob/3b5633de219eec2908723a8e557758cc055d84d1/index.go#L82-L86) makes sure the method is called.
`newIndexFromC()` is used in [`Repository.Index()`](https://github.com/libgit2/git2go/blob/3b5633de219eec2908723a8e557758cc055d84d1/repository.go#L145), but not in [`NewIndex()`](https://github.com/libgit2/git2go/blob/3b5633de219eec2908723a8e557758cc055d84d1/index.go#L90-L101) and [`OpenIndex()`](https://github.com/libgit2/git2go/blob/3b5633de219eec2908723a8e557758cc055d84d1/index.go#L105-L119).

I think this causes memory leaks when we use these functions without calling `Index.Free()` explicitly.

**Comment by carlosmn** [comment]
Yes, that is correct. Those uses do not set the finalizer to free the C memory. It's likely a result of `newIndexFromC()` not existing when those were created.
