### ISSUE TITLE
OpenRepositoryExtended same as OpenRepository 

### ISSUE THREAD

**Issue by soul9** [libgit2/git2go#277]
Since no extra options are passed to [git_repository_open_ext](https://libgit2.github.com/libgit2/#HEAD/group/repository/git_repository_open_ext) the [OpenRepositoryExtended](https://github.com/libgit2/git2go/blob/master/repository.go#L65) function has no extra value compared to the simple OpenRepository

**Comment by carlosmn** [comment]
That's right, none of the extra options supported by `git_repository_open_ext()` are exposed in git2go but if somebody needs those extra options, this is where they would be exposed.

**Comment by carlosmn** [comment]
Fixed via #283
