### ISSUE TITLE
Go 1.6 beta cgo breakage

### ISSUE THREAD

**Issue by ebfe** [libgit2/git2go#278]
With Go 1.6 there are new restrictions on what is allowed to cross the Go - C boundary. 
See golang/go#12416.

    $ go test
    --- FAIL: TestDiffTreeToTree (0.00s)
    panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
    	panic: runtime error: cgo argument has Go pointer to Go pointer
    
    goroutine 15 [running]:
    testing.tRunner.func1(0xc8200827e0)
    	/src/go/src/testing/testing.go:461 +0x192
    github.com/libgit2/git2go.(*Repository).DiffTreeToTree(0xc8201c7140, 0xc820187800, 0xc820187960, 0xc820049ee8, 0x0, 0x0, 0x0)
    	/go/src/github.com/libgit2/git2go/diff.go:589 +0x3c2
    github.com/libgit2/git2go.TestDiffTreeToTree(0xc8200827e0)
    	/go/src/github.com/libgit2/git2go/diff_test.go:80 +0x1a9
    testing.tRunner(0xc8200827e0, 0xa4c490)
    	/src/go/src/testing/testing.go:467 +0x98
    created by testing.RunTests
    	/src/go/src/testing/testing.go:576 +0x879
    exit status 2
    FAIL	github.com/libgit2/git2go	0.047s

**Comment by carlosmn** [comment]
Fixed via #282

**Comment by itamarst** [comment]
I discovered another incompatibility in the Blob support; see PR #302 for fix.
