### ISSUE TITLE
"could not determine kide of name for C.XXX"

### ISSUE THREAD

**Issue by protosam** [libgit2/git2go#281]
I imagine the stable should work against OS provided libgit2 libraries. I'm running CentOS 7, with libgit2 and libgit2-devel installed. I'm running into the following issues:  

On the stable release:  

```
[root@panel gitbox]# cat main.go
package main

import (
    "fmt"
    "gopkg.in/libgit2/git2go.v22" // same problem with v23 as well.
)

func main(){
    repo, err := git.Clone("git://github.com/gopheracademy/gopheracademy-web.git", "web", &git.CloneOptions{})
    if err != nil {
        fmt.Println(err)
    }
}
[root@panel gitbox]# go run main.go
# gopkg.in/libgit2/git2go.v22
could not determine kind of name for C.GIT_CHERRYPICK_OPTIONS_VERSION
could not determine kind of name for C.git_cherrypick
could not determine kind of name for C.git_cherrypick_init_options
could not determine kind of name for C.git_cherrypick_options
```

On the most recent version:  

```
[root@panel gitbox]# cat main.go
package main

import (
    "fmt"
    "github.com/libgit2/git2go"
)

func main(){
    repo, err := git.Clone("git://github.com/gopheracademy/gopheracademy-web.git", "web", &git.CloneOptions{})
    if err != nil {
        fmt.Println(err)
    }
}
[root@panel gitbox]# go run main.go
# github.com/libgit2/git2go
could not determine kind of name for C.GIT_CHECKOUT_DONT_WRITE_INDEX
could not determine kind of name for C.GIT_CHECKOUT_RECREATE_MISSING
```

I'm certain I missing something here. Can anyone point me in the right direction on this?  

Thanks,  
Sam

**Comment by zmarcantel** [comment]
Seeing the same behavior.

```
$ uname -a
Linux nova 3.16.0-31-generic #43~14.04.1-Ubuntu SMP Tue Mar 10 20:13:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ go version
go version go1.5.2 linux/amd64
```

```
$ dpkg -s libgit2-0
Package: libgit2-0
Status: install ok installed
Priority: extra
Section: libs
Installed-Size: 643
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: libgit2
Version: 0.19.0-2
Depends: libc6 (>= 2.15), libssl1.0.0 (>= 1.0.0), zlib1g (>= 1:1.1.4)
Pre-Depends: multiarch-support
Description: low-level Git library
 libgit2 is a portable, pure C implementation of the Git
 distributed version control system core methods provided as a
 re-entrant link-able library with a solid API.
Original-Maintainer: Russell Sim <russell.sim@gmail.com>
Homepage: http://libgit2.github.com/
```

I imagine this has to do with libgit2 version incompatibilities.....
Ubuntu 14.04 has `libgit2-0.19.0-2` as the latest version, but git2go only supports `0.20` and onward?

Ideally I could just import a version-agnostic copy of git2go but I don't see that happening

**Comment by protosam** [comment]
I've also tried compiling against latest release of libgit2 with similar issues.

**Comment by carlosmn** [comment]
Each branch of git2go compiles against the specified version, with master against he latest release, as specified in the README.md. There is no version-agnosic branch because that's impossible. There is no support for libgit2 0.19, IIRC that was before these bindings even started.

If you must use the system-provided old version, you could take the 0.20 version and adapt that, but that version of libgit2 is completely unsupported.

**Comment by zmarcantel** [comment]
Yes, I am aware a version-agnostic library is far too pie in the sky to exist, but one can dream right?

What you say makes absolute sense and since I'm shipping binaries it's irrelevant which version I compile with.
I only bring it up because ubuntu14.04 is such a major target which sadly is behind the times in regards to libgit2.

**Comment by protosam** [comment]
Thanks for getting back to us carlosmn. When I went to compile against libgit2, I downloaded the latest version and tried to also compile against that. Ultimately I was just attempting this for a customer at work, I work as a webhosting Linux Admin. 

It might be beneficial to just update the README.md to indicate some steps for ensuring we get the right libgit2 version onto our box. Like, if we have to switch to a specific branch or something. I think this would clear up some confusion for the version conflicts.

**Comment by JoshWillik** [comment]
I'm also having a hard time installing git2go on the [stock golang docker image](https://hub.docker.com/_/golang/). Being able to use this library with docker would be nice.

**Comment by carlosmn** [comment]
@JoshWillik there's nothing special about docker; you just need to match which version of git2go you're installing with the version of libgit2 you have, or build `next`, which is static.

**Comment by JoshWillik** [comment]
@carlosmn Ah, thank you. I don't hit any missing C.XXX errors when I install next. Thank you!

**Comment by rcshubhadeep** [comment]
@JoshWillik Can you show me the Dockerfile. I am really having a hard time to achieve this. Thanks

**Comment by JoshWillik** [comment]
@rcshubhadeep I don't have this project kicking around anymore, sorry :(
