### ISSUE TITLE
Can't set CreateCommit() to work for initial commit

### ISSUE THREAD

**Issue by elmed** [libgit2/git2go#284]
Hello, 

I have an issue with CreateCommit() for initial commits. the *commit type parameter in CreateCommit does not accept nil, and for the 1st commit I can not pass the commit's parent to the function since there is none. This works fine in libgit2.

 in git2go: repo.CreateCommit(refs, signature, signature, message, tree, commitTarget) // commit target should be nil for the initial commit 
 in libgit2: git_commit_create(&oid_commit, repo, "HEAD", sign, sign,  NULL, message, tree, 0, NULL ); // this works fine and creates an initial commit.

please any idea on what should I pass for the *commit parameter in other to be be able to perform an initial commit ?

thank you.

**Comment by clns** [comment]
Have you seen #259 ?

**Comment by elmed** [comment]
I did not see it before. Thank you this solves my problem.
