### ISSUE TITLE
Repository.LookupReference dropped ?

### ISSUE THREAD

**Issue by ghellings** [libgit2/git2go#290]
Between https://github.com/libgit2/git2go/blob/4eae20ec279d20948aa5a45e0963ae7c4bcb0712/repository.go#L179

and

https://github.com/libgit2/git2go/blob/b4ade2b9c693488aead837a36bc50e86d04950a2/repository.go#L179

LookupReference was removed.  Was this on purpose?

**Comment by carlosmn** [comment]
References moved to the `References` collection. You can look them up and create them there.
