### ISSUE TITLE
Checking out a branch

### ISSUE THREAD

**Issue by amlwwalker** [libgit2/git2go#291]
How do I checkout a branch?
I can open a repo, create a branch, stage changes, commit changes, but what I need to do is checkout an existing branch.
How do you do that?

**Comment by carlosmn** [comment]
You can use [`Repository.CheckoutTree()`](https://godoc.org/github.com/libgit2/git2go#Repository.CheckoutTree) to checkout the files. If by "checkout a branch" you mean switch to that branch, you will also need to update HEAD, e.g. with [`Repository.SetHead()`](https://godoc.org/github.com/libgit2/git2go#Repository.SetHead)
