### ISSUE TITLE
add submodule clone support

### ISSUE THREAD

**Issue by toxeus** [libgit2/git2go#300]
I wanted to initialize and clone submodules using git2go. I came to the conclusion that this is currently not supported because a [part of the clone API](https://github.com/libgit2/libgit2/blob/ec5a43b60ab0dfcb42db8101edfca34be3d62947/src/submodule.c#L1152-L1155) is not implemented in git2go.

Is there a roadmap for this particular feature?

**Comment by carlosmn** [comment]
There is no roadmap. Features are added by people who need them.
