### ISSUE TITLE
Could not determine kind of name for C.GIT_CHECKOUT...

### ISSUE THREAD

**Issue by ajsb85** [libgit2/git2go#303]
```

could not determine kind of name for C.GIT_CHECKOUT_DONT_WRITE_INDEX
could not determine kind of name for C.GIT_CHECKOUT_RECREATE_MISSING
Makefile:8: recipe for target 'install' failed
```

**Comment by carlosmn** [comment]
Check which version of libgit2 you've installed on your system. The git2go branches correspond to the libgit2 version.

**Comment by ajsb85** [comment]
I tried with v22, v23 and v24.
Every version have a different error.
I leave the project.
Good luck.
