### ISSUE TITLE
Race detector issue: 'git2.h' file not found 

### ISSUE THREAD

**Issue by cleung2010** [libgit2/git2go#309]
I am trying to use Go's race detector to check for race conditions in my project, but I am encountering the following error:

```
# github.com/libgit2/git2go
../../libgit2/git2go/blame.go:4:10: fatal error: 'git2.h' file not found
#include <git2.h>
         ^
1 error generated.
```

**Comment by carlosmn** [comment]
There isn't anything here to triage. What version/branch of git2go are you using? Are you running this from within git2go or in your own project? Do you have libgit2 installed?

**Comment by cleung2010** [comment]
Sorry for the vague report. This issue was generated because of a mismatch between the git2go and libgit2 libraries used. This can be closed now.
