### ISSUE TITLE
How to new a ssh Cred by a ssh keypair

### ISSUE THREAD

**Issue by jack230230** [libgit2/git2go#311]
There is a NewCredSshKey func to new a ssh cred only for prividing publickey and private key file path. I want know how to get a Cred by `ssh.PublicKey` and `rsa.Privatekey` which provided by `golang.org/x/crypto.ssh`

see these:
* https://godoc.org/golang.org/x/crypto/ssh#PublicKey
* https://godoc.org/crypto/rsa#PrivateKey

On an other word, would you privide a NewCredSshKey by pass []byte of the public key and private key?

**Comment by carlosmn** [comment]
This doesn't use Go's crypto so we have no way to pass this to libssh2. There is constructor to pass in a key in memory if the libssh2 version against which libgit2 was built supports it, which might be of use.

But as for accepting Go crypto's SSH types, you'd have to add the functionality of extracting that data into something libssh2 can consume.
