### ISSUE TITLE
How to run git log commands?

### ISSUE THREAD

**Issue by codefx9** [libgit2/git2go#312]
Sorry for asking newbie questions. I am interested in running `git log` commands from go. I see that C# version has support for this (https://github.com/libgit2/libgit2sharp/wiki/git-log) . Does this GO version also  support for similar `git log` commands? I did some quick searching for "query" and "filter" keywords and I did not find anything. Thanks.

**Comment by carlosmn** [comment]
This isn't about running git commands, but about handling Git data. libgit2sharp doesn't offer `git log` commands any more than git2go does, it just makes it _look_ like the options you'd pass to it.
