### ISSUE TITLE
BranchIterator ForEach error is not nil

### ISSUE THREAD

**Issue by cleung2010** [libgit2/git2go#315]
`func (i *BranchIterator) ForEach(f BranchIteratorFunc) error` returns empty string instead of `nil` even if there are no errors from `BranchIteratorFunc`

Here is a reproducible example of the bug:
https://gist.github.com/cleung2010/2d483971f64dd0db1e6c6bd314356a19

**Comment by netnose** [comment]
It is the expected behavior. You can find an example of how to use the BranchIterator and handle this error correctly [in its tests](https://github.com/libgit2/git2go/blob/master/branch_test.go#L50).

**Comment by cleung2010** [comment]
Awesome, thanks for pointing it out!
