### ISSUE TITLE
Please provide instructions on how to run git2go in a Docker container

### ISSUE THREAD

**Issue by danielfbm** [libgit2/git2go#327]
I am sorry, this is not really an issue for me right now. I actually already solved it creating a Docker image and pushing it to the Dockerhub. I already tested cloning with HTTPS and SSH, but I would also really appreciate if you guys could give me your feedback or if you could improve on what I have done. Here you can find the [docker image](https://hub.docker.com/r/danielfbm/docker-go-libgit2) and the [repo](https://github.com/danielfbm/docker-go-libgit2)

I had some trouble to get started and spent a lot of time trying to figure this out, so I decided to post it here so more people could get involved.
:)

**Comment by stephenrlouie** [comment]
@danielfbm - thanks for posting this, I'm running into similar problems. I have git2go in a project and have been fighting to get it to run in a container.

I copied your Dockerfile but am still seeing `there is no TLS stream available` when I Clone

Do you have any ideas?

**Comment by stephenrlouie** [comment]
*resolved*: didn't properly cross compile. I thought it was a lack of libssh2, turned out the .a file and .pc files were incorrect
