### ISSUE TITLE
git2go should ensure -DGIT_THREADS was used for libgit2 

### ISSUE THREAD

**Issue by hanwen** [libgit2/git2go#329]
It's apparently possible to link libgit2 into a git2go binary, with thread-safety switched off. For git2go this does not make any sense; git2go should crash if libgit2 wasn't compiled with -DGIT_THREADS.

**Comment by carlosmn** [comment]
You would have to choose to build your shared libgit2 without threading support, which would already indicate your choice not to run anything with threads, so I'm not sure how that happens accidentally with anything more-or-less recently.

But yes, that doesn't make a lot of sense with Go. It probably make sense to check for the threading capability and error out (maybe the only option is panic?) if we link against a version without it.

**Comment by carlosmn** [comment]
Fixed via #354
