### ISSUE TITLE
could not determine kind of name for C.GIT_CHECKOUT_DONT_WRITE_INDEX

### ISSUE THREAD

**Issue by oren** [libgit2/git2go#333]
I am trying to `go build` this repo - https://notabug.org/rain1/clay and see this error:

```
could not determine kind of name for C.GIT_CHECKOUT_DONT_WRITE_INDEX
```

I am on Ubuntu 15.10, go version go1.6 linux/amd64

**Comment by carlosmn** [comment]
The version of libgit2 you have installed is not the one that the version of git2go you're compiling works against.

**Comment by oren** [comment]
thanks! I upgraded to ubuntu 16.04 and I am able to run the build command.
