### ISSUE TITLE
SEGFAULT on git.Clone() when no auth callback provided

### ISSUE THREAD

**Issue by AaronO** [libgit2/git2go#335]
When cloning without auth, I feel it's safe to assume that the caller doesn't need to provide an auth callback.
## Test case

I wrote a test case that reproduces the error: https://gist.github.com/AaronO/4bea94ae93885d4a05af7cc417f72e1f

If you set `enableAuth` to `true`, which enables a remote auth callback, you'll see that it no longer segfaults.
## What happens

libgit2's `git_clone` segfaults
## What should happen

Not segfault.
## Solution

Not 100% clear at the moment, I haven't done enough digging to see if `git2go` doesn't populate the remote callbacks as expected or if this is a problem in `libgit2` itself. Or if in fact the caller is required to set this callback even when no auth is desired.

**Comment by carlosmn** [comment]
This probably happens because we `return 0` when none is specified on the Go side, which violates the API. We should be returning either `GIT_PASSTHROUGH` for versions that support it, or possibly `GIT_EUSER` and set an error message.

**Comment by carlosmn** [comment]
I just merged #319 which performs this conversion to return PASSTHROUGH if there are no callbacks actually set.

**Comment by AaronO** [comment]
@carlosmn Thanks, much appreciated.
