### ISSUE TITLE
"Package 'zlib', required by 'libgit2', not found"

### ISSUE THREAD

**Issue by Happy-Ferret** [libgit2/git2go#343]
So I've been at this for more than a few hours now (kudos at Microsoft for making everything harder! It only took me five minutes to set everything up on my Ubuntu and RedHat systems. Now where is the fun in that...), followed every tutorial in the internet and am still failing miserably at the `make install` step.

Steps I followed:
- Clone git2go
- Check out `next` branch
- Fetch libgit2 submodule
- Add `-G "MinGW Makefiles"\` to the `cmake` flags inside [script/build-libgit2-static.sh](https://github.com/libgit2/git2go/blob/next/script/build-libgit2-static.sh).
- Run `script/build_libgit2-static.sh`
- Run `make install`

What's the proper way to receive the zlib package or, alternatively, how would I remove it from the whole process (since it seems to be an optional dependency anyways)? I already tried editing libgit2's `CMakeLists.txt` but that ends up in a failed build.

**Comment by Happy-Ferret** [comment]
I have alleviated this and a few other issues now.

Will try and come up with a short write-up later, to spare fellow developers from going through the same pains.

**Comment by carlosmn** [comment]
zlib is not an optional dependency, but libgit2 will use its vendored copy if it is not found in the system. If it does not, that's a bug in the build system.

You don't mention, however, what environment you're building this in. libgit2 does not support the older mingw but only mingw-w64.
