### ISSUE TITLE
Unable to compile getting ./blame.go:4:18: fatal error: git2.h: No such file or directory

### ISSUE THREAD

**Issue by ankurmittal** [libgit2/git2go#375]
Hi while running make I am getting

./script/build-libgit2-static.sh
+ VENDORED_PATH=vendor/libgit2
+ cd vendor/libgit2
+ mkdir -p install/lib
+ mkdir -p build
+ cd build
+ cmake -DTHREADSAFE=ON -DBUILD_CLAR=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=../install ..
-- Could NOT find HTTP_Parser (missing:  HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY) 
-- http-parser version 2 was not found; using bundled 3rd-party sources.
-- Checking for module 'libssh2'
--   No package 'libssh2' found
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/google/home/anmittal/repos/go/src/github.com/libgit2/git2go/vendor/libgit2/build
+ cmake --build .
make[1]: Entering directory `/usr/local/google/home/anmittal/repos/go/src/github.com/libgit2/git2go/vendor/libgit2/build'
make[2]: Entering directory `/usr/local/google/home/anmittal/repos/go/src/github.com/libgit2/git2go/vendor/libgit2/build'
make[3]: Entering directory `/usr/local/google/home/anmittal/repos/go/src/github.com/libgit2/git2go/vendor/libgit2/build'
make[3]: Leaving directory `/usr/local/google/home/anmittal/repos/go/src/github.com/libgit2/git2go/vendor/libgit2/build'
[100%] Built target git2
make[2]: Leaving directory `/usr/local/google/home/anmittal/repos/go/src/github.com/libgit2/git2go/vendor/libgit2/build'
make[1]: Leaving directory `/usr/local/google/home/anmittal/repos/go/src/github.com/libgit2/git2go/vendor/libgit2/build'
go install ./...
\# github.com/libgit2/git2go
./blame.go:4:18: fatal error: git2.h: No such file or directory
 #include <git2.h>
                  ^
compilation terminated.
make: *** [install] Error 2

**Comment by ankurmittal** [comment]
`make static` is working, `make` is not

**Comment by carlosmn** [comment]
The dynamic one is looking for libgit2 installed on the system. If you don't have it installed, then it won't be able to find it.

**Comment by Fjolnir-Dvorak** [comment]
I am confused what solved this issue. When I am trying to compile git2go static I am getting the same issue as above with the message: "git2.h No such file or directory", after the compiler successfully compiled libgit2 to libgit2.a
