### ISSUE TITLE
grsec: denied RWX mprotect

### ISSUE THREAD

**Issue by powerman** [libgit2/git2go#377]
Is it possible to avoid using RWX memory? This breaks on GrSecurity-patched Linux kernel:
```
$ go test --tags "static"
/tmp/go-build620243938/github.com/libgit2/git2go/_test/git2go.test: error while loading shared libraries: cannot make segment writable for relocation: Permission denied
exit status 127
FAIL	github.com/libgit2/git2go	0.002s
```
To work around:
```
$ go test --tags "static" -o test
/home/powerman/gocode/src/github.com/libgit2/git2go/test: error while loading shared libraries: cannot make segment writable for relocation: Permission denied
exit status 127
FAIL	github.com/libgit2/git2go	0.002s
$ paxctl-ng -m ./test
$ ./test
PASS
```
If same thing happens with every go binary which use this package then it's very inconvenient. 😞

**Comment by powerman** [comment]
Looks like `go test --tags "static" -buildmode=pie` works too, but compilation takes a lot of time.

**Comment by carlosmn** [comment]
I don't see in that output where the error comes from. It it trying to load one of the libraries we use for networking/crypto? Is it git2go loading it or the go runtime by itself?

**Comment by powerman** [comment]
I don't know. git2go is only Go+C packages I've used so far. I suppose you shouldn't mark memory both executable and writeable at same time, even while loading libraries into that memory. Probably PaX docs should contains more details about how to code this in safe way.
