### ISSUE TITLE
build issue using git2go: gopkg.in/libgit2/git2go.v25/submodule.go:339: ptr.clone_checkout_strategy undefined

### ISSUE THREAD

**Issue by craigmj** [libgit2/git2go#378]
I've installed git2go.v25 with `go get -d`, and have installed libgit2 from the repo, so that:
    $ pkg-config --cflags --libs libgit2
    -I/usr/local/include -L/usr/local/lib -lgit2
and
    $  ls /usr/local/lib/libgit2*
    /usr/local/lib/libgit2.so  /usr/local/lib/libgit2.so.0.25.0  /usr/local/lib/libgit2.so.25
So I reckon I've got the install right. But when I build my go program, I get:
    vendor/gopkg.in/libgit2/git2go.v25/submodule.go:339: ptr.clone_checkout_strategy undefined (type *C.struct_git_submodule_update_options has no field or method clone_checkout_strategy)
Any ideas?

**Comment by apflieger** [comment]
versions of git2go and libgit2 incompatible maybe ?

**Comment by craigmj** [comment]
I'm guessing not since the installed git2go is .v25 and the installed libgit2 seems to be 0.25.0 - assuming the lib filenames reflect correctly. Also if I look in `/usr/local/include/git2/version.h` I have:

    #define LIBGIT2_VERSION "0.25.0"

So I'm guessing there's nothing wrong with the versions... or at least it looks to me like they are declaring themselves compatible...

**Comment by carlosmn** [comment]
Did you install a libgit2 release of v0.25.x? The development versions generally don't change the SOVERSION until a release is close. Until then it's generally not useful to install them system-wide.

**Comment by craigmj** [comment]
I've created a repo that illustrates the issue:

https://github.com/craigmj/git2go-issue-378

It should be sufficient to checkout and run `./build.sh init` : BUT be warned, it installs the apt `golang` package, and installs libgit2 to /usr/local/libgit2 - so perhaps run in a VM or a clean Linux container.

**Comment by carlosmn** [comment]
This is what I said, you're not installing a v0.25.x version of libgit2, but whatever is in master, which is not that, even if the SOVERSION hasn't changed yet. If you want the latest v0.25 maintenance code from the repository, you can get it from the `maint/v0.25` branch.

**Comment by craigmj** [comment]
Many thanks - that fixed the build! Now just to get it to find the .so... :)
