### ISSUE TITLE
Update libgit2

### ISSUE THREAD

**Issue by mschenk42** [libgit2/git2go#384]
Will you be updating libgit2 in the near future?  Looking to include the latest changes in my project.  Thanks.

**Comment by dtmistry** [comment]
yeah it looks like the 0.26 branch still relies on libgit v0.25

```
# gopkg.in/libgit2/git2go.v26
../../../gopkg.in/libgit2/git2go.v26/git_dynamic.go:10:3: error: "Invalid libgit2 version; this git2go supports libgit2 v0.25"
# error "Invalid libgit2 version; this git2go supports libgit2 v0.25"
  ^
1 error generated.
```

**Comment by carlosmn** [comment]
That was a bug #399 

This gets updated whenever there's a release or whenever I can spare some time to this project.
