### ISSUE TITLE
Git2Go doesn't push changes anymore

### ISSUE THREAD

**Issue by faridbouchdak** [libgit2/git2go#392]
Hi, I recently started to work with github and git2go.
Awesome work on the app btw!
Since yesterday Git2Go doesn't push my changed to github.
I have two public repositories and neither are being updated.
I didnt change my username or password for github.
I tried to Google my problem, but no results for my issue found.
Any help is appreciated.
I have added a screenshot.
![img_0001](https://user-images.githubusercontent.com/29151855/27984592-15a6daec-63da-11e7-933f-30cfac1a919d.PNG)

**Comment by carlosmn** [comment]
It looks like you're after the git2go iOS app. This project is a wrapper for the libgit2 library.
