### ISSUE TITLE
Type mismatch for unsafe.Pointer at patch.go

### ISSUE THREAD

**Issue by fudanchii** [libgit2/git2go#412]
A bit confused since travis doesn't report this error. But in my machine go complaining that it can _not_ use `unsafe.Pointer` as `*C.char` at compile

```
./patch.go:86: cannot use newPtr (type unsafe.Pointer) as type *C.char in argument to func literal
```
This can be fixed by casting newPtr explicitly at line 86 like so:

``` go
ecode := C.git_patch_from_buffers(&patchPtr, oldPtr, C.size_t(len(oldBuf)), cOldPath, (*C.char)(newPtr), C.size_t(len(newBuf)), cNewPath, copts)
```

Anyone has any idea about this? I had probably missed something obvious 🤔

**Comment by carlosmn** [comment]
What version of git2go are you using? Are you building statically or dynamically? If dynamically, does the libgit2 version match? The most likely source of this would seem to be that you're trying to build `master` dynamically, which doesn't work with any published version of libgit2.

**Comment by fudanchii** [comment]
Ah right, apologies for the incomplete info.
I build statically from master. Tested with either master libgit2 or the rev used in travis CI.

It can compile successfully when I cast the `newPtr` explicitly as mentioned above. Is that approach correct?

Thanks before!

**Comment by fudanchii** [comment]
Apparently I did compile libgit2 statically, but I built git2go dynamically.  
Calling `go build -tags static` works. Sorry for the noise, and thank you!
