### ISSUE TITLE
Unit tests failing with SIGSEGV: segmentation violation in Go

### ISSUE THREAD

**Issue by scshitole** [libgit2/git2go#415]
Hello folks,
I am getting this error when I run a unit test in Go, not sure where to start looking ..has anybody seen this before ? the tests were running fine before I upgraded to terraform 10.X
2017/10/17 13:28:28 Resource schema
--- PASS: TestProvider (0.00s)
=== RUN   TestBigipLtmIRule_create
--- PASS: TestBigipLtmIRule_create (0.91s)
=== RUN   TestBigipLtmIRule_import
--- FAIL: TestBigipLtmIRule_import (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x15ffde7]

goroutine 172 [running]:
testing.tRunner.func1(0xc4202ac000)
	/usr/local/Cellar/go/1.9/libexec/src/testing/testing.go:711 +0x2d2
panic(0x170f200, 0x1c008d0)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource.testResource(0xc420017140, 0x11, 0x0, 0xc42018c240, 0x8f, 0xc4203a6840, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/shitole/work/src/github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource/testing.go:737 +0x37
github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource.testStepImportState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/shitole/work/src/github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource/testing_import_state.go:30 +0x1452
github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource.Test(0x1bd2ae0, 0xc4202ac000, 0x0, 0xc4202ef310, 0xc4201bb2c0, 0x0, 0x0, 0x180a578, 0xc42029e580, 0x1, ...)
	/Users/shitole/work/src/github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource/testing.go:440 +0x535
github.com/terraform-provider-f5/bigip.TestBigipLtmIRule_import(0xc4202ac000)
	/Users/shitole/work/src/github.com/terraform-provider-f5/bigip/resource_bigip_ltm_irule_test.go:42 +0x241
testing.tRunner(0xc4202ac000, 0x1809ff0)
	/usr/local/Cellar/go/1.9/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9/libexec/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/terraform-provider-f5/bigip	1.037s
make: *** [testacc] Error 1
SJC-ML-SHITOLE:terraform-provider-f5 shitole$

**Comment by carlosmn** [comment]
This is the git2go project, not terraform.
