### ISSUE TITLE
On every commit git2go takes an unaware picture when I dont want it to.

### ISSUE THREAD

**Issue by AraHaan** [libgit2/git2go#418]
On my iPhone 5s for some reason after updating to the latest version it does what the tutle of this issue states, it saves an picture of me with the commit hash and the commit name in white text. I do not expect or want this because then it would clutter my iPhone with useless images that I then have to manually delete.

**Comment by carlosmn** [comment]
It looks like you're talking about the git2go iOS app. This repository has nothing to do with it.

**Comment by AraHaan** [comment]
Then where do I report this to them then?

**Comment by carlosmn** [comment]
I don't know. This project has no association with that application.
