### ISSUE TITLE
could not determine kind of name for C.git_blob_create_fromstream

### ISSUE THREAD

**Issue by lightsing** [libgit2/git2go#433]
![make test-static](https://user-images.githubusercontent.com/15951701/36348375-291f9156-14a9-11e8-9010-bb70bc9e6284.png)

`make test-static` pass
but fail in my porject build

![go build](https://user-images.githubusercontent.com/15951701/36348380-41502696-14a9-11e8-8c13-8c391cb73480.png)

```
> $ go version
go version go1.6.2 linux/amd64
> $ uname -a
Linux DESKTOP-D3AKR8S 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by peteryates** [comment]
I too can't get beyond this when trying to install via `go get` in a docker image (`centos:centos7` with `libgit2` and `libgit2` installed via [EPEL 7](https://fedoraproject.org/wiki/EPEL))

```bash
[root@b480b0676f44 myproject]# go get gopkg.in/libgit2/git2go.v25
# gopkg.in/libgit2/git2go.v25
could not determine kind of name for C.git_blob_create_fromstream
could not determine kind of name for C.git_blob_create_fromstream_commit
```

```bash
[root@b480b0676f44 backend]# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build208236803=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by peteryates** [comment]
So it would appear that the version mismatch (libgit2@0.24.6 vs git2go@0.25) was causing the problem; changing my image to `fedora:25` and using a [more up-to-date libgit2 rpm](https://koji.fedoraproject.org/koji/buildinfo?buildID=839245) solved it for me.

**Comment by carlosmn** [comment]
Indeed this kind of issue is due a mismatch in the installed libgit2 on the system vs the version of git2go. Versions before v26/v0.26 did not have a version check in the git2go so it would fail to find a symbol instead of erroring out with a message explicitly about the supported version.
