### ISSUE TITLE
fatal error: 'git2.h' file not found,  while `make install`

### ISSUE THREAD

**Issue by momentofawsome** [libgit2/git2go#437]
After executing the  following steps (on my Mac)
1. cd $GOPATH/src/github.com/libgit2/git2go
2. git submodule update --init
3. make install 

This is the resulting Error. 

```
go install ./...
# github.com/libgit2/git2go
./blame.go:4:10: fatal error: 'git2.h' file not found
#include <git2.h>
         ^~~~~~~~
1 error generated.
make: *** [install] Error 2
```

it does NOT end here after manually dropping the `*.h` 
**from**: https://github.com/libgit2/libgit2/tree/master/include
**into**:  $GOPATH/src/github.com/libgit2/git2go
there is another error

**Comment by carlosmn** [comment]
`make install` does the dynamic linking. If you do not have the libgit2 development package or have manually installed libgit2 into your system, it won't be able to find it.

See https://github.com/libgit2/git2go/tree/e57025a372f882df8ee7dbc47dc7d4ec6eddcc55#master-branch-or-static-linking for instructions to use on `master` and/or use static linking.
