### ISSUE TITLE
DiffOptionsFlag causes an overflow in Windows

### ISSUE THREAD

**Issue by buddyspike** [libgit2/git2go#439]
When building v27 branch on ~~Windows~~ for 32bit, I get this error:
```
vendor\github.com\libgit2\git2go\diff.go:441: constant 2147483648 overflows DiffOptionsFlag
```
I think the type of `DiffOptionsFlags` should be `uint` because in `git2` headers they are:
https://github.com/libgit2/libgit2/blob/master/include/git2/diff.h#L214

**Comment by carlosmn** [comment]
As mentioned in #440 we can't decide on our own to make it unsigned, but libgit2 has reduced the max value so it works again and this is included in master and will be part of the next release.

We can't change it in the current releases so this is as fixed as it's going to get.
