### ISSUE TITLE
recipe for target 'install-static' failed in Makefile:14

### ISSUE THREAD

**Issue by RedChiken** [libgit2/git2go#453]
I tried to build this code and when I run `make install-static`, this problem occur.

`go install --tags "static" ./...
go install: no install location for directory /home/redchiken/go/src/github.com/libgit2/git2go outside GOPATH
	For more details see: go help gopath
Makefile:14: recipe for target 'install-static' failed
make: *** [install-static] Error 1
`

I get this code by go get syntax, so code saved in $GOPATH/src/github.com/libigt2/git2go.

Can you check this problem?

**Comment by carlosmn** [comment]
It looks like this is an issue with your GOPATH configuration and where you put git2go, i don't see how I can look at anything.
