### ISSUE TITLE
cannot find module providing package

### ISSUE THREAD

**Issue by particledecay** [libgit2/git2go#454]
With the following import:
```go
import (
    "github.com/libgit2/git2go.v27"
)
```
I'm getting this error when attempting to build:
```
import "github.com/libgit2/git2go.v27": cannot find module providing package github.com/libgit2/git2go.v27
```
I have `libgit2` installed:
```
➜ brew list --versions | grep libgit
libgit2 0.27.4
```

I'm using go-1.11beta3 and this is a project outside of `$GOPATH`. I'm using go modules for this project, and everything built correctly until I added git2go.

**Comment by carlosmn** [comment]
There is no repository at `github.com/libgit2/git2go.v27` so I don't know what you were expecting to find there. There is a `gopkg.in` of a similar URL which will point you to the branch named `v27` but I don't know how modules interact with either of those URLs.

**Comment by ParticleDecay** [comment]
Well, I was following the instructions in the [README](https://github.com/libgit2/git2go/blob/master/README.md#which-branch-to-use). I must have misunderstood.

**Comment by carlosmn** [comment]
Those instructions say to use the wrapping service `gopkg.in`.

**Comment by carlosmn** [comment]
Note however that those instructions are for vanilla go i.e. straight up `go get`. If you're using a package manager it might have different requirements or ways to specify which branch to use which it should document itself.

**Comment by damienstanton** [comment]
Documentation on how to use Go modules can be confusing, and I think this is an order of operations problem rather than anything wrong with the git2go docs.

@particledecay please see this repo as a minimal example of `git2go` working correctly with current `go mod` practices: https://github.com/damienstanton/git2go-test
