### ISSUE TITLE
tree.Walk() is missing a context for callbacks

### ISSUE THREAD

**Issue by missionsix** [libgit2/git2go#461]
The v26 API for libgit2 specifies a `payload` context to be passed to the callback method:

From tree.h:
```c
/** Callback for the tree traversal method */
typedef int (*git_treewalk_cb)(
const char *root, const git_tree_entry *entry, void *payload);

/*
 * @param tree The tree to walk
 * @param mode Traversal mode (pre or post-order)
 * @param callback Function to call on each tree entry
 * @param payload Opaque pointer to be passed on each callback
 * @return 0 or an error code
 */
GIT_EXTERN(int) git_tree_walk(
	const git_tree *tree,
	git_treewalk_mode mode,
	git_treewalk_cb callback,
void *payload);
```

The `tree.Walk` call omits the opaque context:
```go
type TreeWalkCallback func(string, *TreeEntry) int

func (t Tree) Walk(callback TreeWalkCallback) error
```

Which makes it extremely difficult to recursively walk trees.

**Comment by missionsix** [comment]
Propsal, use the empty interface:

```go
type TreeWalkCallback func(string, *TreeEntry, interface{}) int

func (t Tree) Walk(callback TreeWalkCallback, interface{}) error
```

**Comment by carlosmn** [comment]
libgit2 has a payload because that's how you capture the context that you need for closure-like behaviour in C. In Go you can access whatever external context you need within the function you pass as a callback. This is the same way as everything else that takes a callback in Go (and many other languages) behave.

**Comment by missionsix** [comment]
I understand, but this style forces your callback to become a closure over some scoped variables.

Using a context, similar to C style, allows for scope isolation.   I'm not against that style for some things, but with a callback that has to do a lot of work, it's better to move it out to a separate function, where you loose the closure.

**Comment by lhchavez** [comment]
what's wrong with

```go
type explicitClosure struct {
   message string
}
func (c *explicitClosure) Walk (string, *TreeEntry) int {
   fmt.Printf("Hello, %s!\n", c.message)
   return 0
}

...

c := &explicitClosure{
  message: "world",
}
tree.Walk(c.Walk)
```

**Comment by carlosmn** [comment]
This is also exactly how the Go stdlib handles this https://golang.org/pkg/path/filepath/#Walk though I'm not particularly a fan of these constructions either way.
