### ISSUE TITLE
Please add support for libgit2 0.28

### ISSUE THREAD

**Issue by dmgk** [libgit2/git2go#502]
```
$ pkg-config --modversion libgit2
0.28.1
```
```
$ go build
# .../src/gopkg.in/libgit2/git2go.v27
./git_dynamic.go:10:3: error: "Invalid libgit2 version; this git2go supports libgit2 v0.27"
# error "Invalid libgit2 version; this git2go supports libgit2 v0.27"
  ^
1 error generated.
```

**Comment by ezwiebel** [comment]
I've got the same kind of issue (or I think so)
It looks like git_static has been moved forward to libgit2 v0.28 where git_dynamic is still on libgit2 v0.27... is that a normal state ?

**Comment by mark-rushakoff** [comment]
ping @carlosmn 

Homebrew is on libgit2 v0.28.1 as of today. I'm having trouble finding an obvious way to downgrade homebrew to use v0.27, to become compatible with git2go.

**Comment by bored-engineer** [comment]
@mark-rushakoff You can just install the older formula by URL to get libgit v0.27.8:
```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/19dee2bd48ec0443e1f4a90bbdae0b9b8ef7da98/Formula/libgit2.rb
```

**Comment by MaiReo** [comment]
@bored-engineer 
use v0.27.8 get
```
could not determine kind of name for C.git_buf_dispose
```
since the git_buf_dispose comes from v0.28
https://libgit2.org/libgit2/#v0.28.1/group/buf/git_buf_dispose

**Comment by YongHaoWu** [comment]
@carlosmn Is there anything we can do to make it support v0.28?

**Comment by Muhammad-Adel** [comment]
commit 5fda6dd  only covers the static build. The dynamic build against 0.28 still fails.

**Comment by pscheid92** [comment]
Is this project dead or something?
I still have problems with 0.28 …

**Comment by lhchavez** [comment]
#515 has been merged and this problem should be solved.

**Comment by muv1** [comment]
I had same problem, turned out I was using:

~~~go
import "github.com/libgit2/git2go"
~~~

instead of:

~~~go
import "github.com/libgit2/git2go/v29"
~~~

https://github.com/libgit2/git2go#which-go-version-to-use
