### ISSUE TITLE
Makefile errors on macOS 10.14.4

### ISSUE THREAD

**Issue by mastahyeti** [libgit2/git2go#504]
I'm running macOS 10.14.4

```
$ pwd
/Users/mastahyeti/Projects/go/src/github.com/libgit2/git2go
$ echo $GOPATH
/Users/mastahyeti/Projects/go
$ /bin/sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
$ make install-static
./script/build-libgit2-static.sh
++ cd ./script/build-libgit2-static.sh/../..
./script/build-libgit2-static.sh: line 5: cd: ./script/build-libgit2-static.sh/../..: Not a directory
+ ROOT=
make: *** [build-libgit2] Error 1
```

Let me know if there's any other details I can provide.

**Comment by amcdawes** [comment]
This has something to do with the line
`ROOT="$(cd "$0/../.." && echo "${PWD}")"`
I was able to get it to work by replacing with a hard-coded path:
`ROOT="/Users/dawe7269/go/src/github.com/libgit2/git2go"`
I'm no shell-script expert, but something fishy about `cd "$0/../.."`

**Comment by mastahyeti** [comment]
I had the same workaround (sorry for not updating this). Just hardcoding the path gets things working.

**Comment by chemprofra** [comment]
Thanks for this thread. The hardcoded path worked in my application. Bliss!

For those, like me, who are not as experienced in Unix, terminals and the like, here is a little help. Navigate to the file: build-libgit2-static.sh

That file can be found at: go/src/github.com/libgit2/git2go/script/build-libgit2-static.sh

Open the build-libgit2-static.sh file and replace the line

ROOT="$(cd "$0/../.." && echo "${PWD}")"

with the suggested code:

ROOT="/Users/XXXXX/go/src/github.com/libgit2/git2go"

where XXXXX is specific to your machine. 

BTW, the "$0" is discussed [here](https://unix.stackexchange.com/questions/280454/what-is-the-meaning-of-0-in-the-bash-shell).

**Comment by lhchavez** [comment]
#503 has landed, and this problem should be no more!
