### ISSUE TITLE
any plans to implement grep and log?

### ISSUE THREAD

**Issue by digininja** [libgit2/git2go#517]
Are there any plans to implement the grep command to search the repo for a given regex and log to list all the commit messages?

**Comment by lhchavez** [comment]
We aim for compatibility with https://libgit2.org. There's no direct grep functionality there (so we won't support it), but one can achieve both with [`Repository.Walk`](https://godoc.org/github.com/libgit2/git2go#Repository.Walk), which allows the caller to iterate through commits in a repository.
