### ISSUE TITLE
Stringer for ErrClass and ErrCode ?

### ISSUE THREAD

**Issue by slyphon** [libgit2/git2go#543]
The functionality might already exist somewhere, but it seems like it'd be useful for error reporting to make a stringer for ErrClass and ErrCode to return human-readable names for the corresponding constants.  

It'd mean that `go generate` would have to be run when the relevant constants were changed, but it seems like this should be relatively easy to do.

Would you accept a pull request that set this up?

**Comment by lhchavez** [comment]
there's precedent for that (e.g. #523) so PR away!

now that you mention it, it may be worth adding an Action to check whether all the `go generate`d files are up to date. that we can do separately.
