### ISSUE TITLE
Could not determine kind of name for C.GIT_BLAME_IGNORE_WHITESPACE

### ISSUE THREAD

**Issue by utkarsh2102** [libgit2/git2go#711]
Hey,

Whilst building git2go v31.4.3 with libgit2 v1.0.1, I get a build failure with the following error:
`src/gopkg.in/libgit2/git2go.v31/blame.go:51:54: could not determine kind of name for C.GIT_BLAME_IGNORE_WHITESPACE`

I am not sure what's wrong, any ideas?

**Comment by lhchavez** [comment]
per https://github.com/libgit2/git2go/pulls it should be `v30`, not `v31` if you need compatibility with libgit2 v1.0. `v31` requires libgit2 v1.1.

**Comment by utkarsh2102** [comment]
Aah, I am terribly sorry for not taking a look at that earlier. Thanks for your work, anyhow! :)

**Comment by lhchavez** [comment]
> Aah, I am terribly sorry for not taking a look at that earlier. Thanks for your work, anyhow! :)

no worries :)
