### ISSUE TITLE
remote.Push triggers an infinite callback loop

### ISSUE THREAD

**Issue by neel1996** [libgit2/git2go#731]
I have been trying to push changes to my remote repo and the `remote.Push` keeps calling the `CredentialsCallback` without an end. 

The callback `CredentialsCallback` returns a new credential using the supplied SSH key-pair and callback keeps getting invoked without terminating.

Sample code :

``` go
remoteCallbacks := git2go.RemoteCallbacks{
    CredentialsCallback: func(url string, userName string, credType git2go.CredentialType) (*git2go.Credential, error) {
           fmt.Pritnln("Inside callback...")
           cred, err := git2go.NewCredentialSSHKey(userName, "PUB_FILE_PATH", "PRIVATE_KEY_FILE_PATH", "")
           return cred, err
   },
   CertificateCheckCallback: func(cert *git2go.Certificate, valid bool, hostname string) git2go.ErrorCode {
            return 0
   },
}

pushOption := &git2go.PushOptions{
    RemoteCallbacks: remoteCallbacks,
}

err := remote.Push([]string{targetRefPsec}, pushOption)
```

In the console I get no error and _"Inside callback..."_ keeps printing on a loop 

Is this a known issue or Am I doing something wrong ?

**Comment by lhchavez** [comment]
the first time the credentials callback is invoked _without an explicit username_ in the remote URLs, `credType` will be [`git2go.CredentialTypeUsername`](https://godoc.org/github.com/libgit2/git2go#CredentialType). When that happens, the callback is expected to return a [`git2go.NewCredentialUsername`](https://godoc.org/github.com/libgit2/git2go#NewCredentialUsername). _then_ it will be called again with a different `credType`, where the expected credential should now be returned.

can you try opening an issue against https://github.com/libgit2/libgit2 about this? This interface could be improved to make failures more obvious.
