### ISSUE TITLE
Some parts of the code use 'error' instead of 'err'

### ISSUE THREAD

**Issue by mbfr** [libgit2/git2go#745]
This is a minor issue, but some of the code uses `error` instead of `err` which conflicts with the builtin `error` interface type, as well as not being in line with the Go style

**Comment by mbfr** [comment]
eg https://github.com/libgit2/git2go/blob/2fd0495c43c4a54a02e2bbfca886687621f83f9f/git.go#L203

**Comment by suhaibmujahid** [comment]
Thank you @mbfr for reporting this. I will open a PR to fix the variable names.
