### ISSUE TITLE
error "Invalid libgit2 version; this git2go supports libgit2 between v1.2.0 and v1.2.0"

### ISSUE THREAD

**Issue by yermulnik** [libgit2/git2go#839]
I'm trying to build/install another project which depends on `git2go`: https://github.com/askgitdev/askgit/issues/197
And it looks like latest `git2go` doesn't support latest `libgit2`:
```
[…]
# github.com/libgit2/git2go/v32
/home/giermulnik/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/libgit2/git2go/v32@v32.0.4/Build_system_dynamic.go:12:3: error: #error "Invalid libgit2 version; this git2go supports libgit2 between v1.2.0 and v1.2.0"
   12 | # error "Invalid libgit2 version; this git2go supports libgit2 between v1.2.0 and v1.2.0"
      |   ^~~~~

[…]
```
Any clue on how do I overcome/fix this issue?
Thanks

**Comment by yermulnik** [comment]
@lhchavez Thanks!

**Comment by lhchavez** [comment]
https://github.com/libgit2/git2go/pull/840 and https://pkg.go.dev/github.com/libgit2/git2go/v33 :tada:
