### ISSUE TITLE
Missing v34 blocks the use of v35

### ISSUE THREAD

**Issue by pjbgf** [libgit2/git2go#938]
Go does not seem to be able to use the newly created git2go `v35` as a `v34` does not exist.

```bash
$ go get -d github.com/libgit2/git2go
[module path "github.com/libgit2/git2go/v34" (and .../v35/go.mod does not exist) at revision v35.0.0](go: github.com/libgit2/git2go/v35@v35.0.0: go.mod has non-.../v35 module path "github.com/libgit2/git2go/v34" (and .../v35/go.mod does not exist) at revision v35.0.0)
```

EDIT: After digging into it further, I noticed that the Git tag `v35` is pointing to a commit in which the Go module version is `v34`.

**Comment by lhchavez** [comment]
v34.0.0 has been created! https://github.com/libgit2/git2go/releases/tag/v34.0.0
